//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LazyMigrate.Config {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SoftwareDate {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SoftwareDate() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LazyMigrate.Config.SoftwareDate", typeof(SoftwareDate).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Security Update;Hotfix;Update for;KB;Cumulative Update;Microsoft Visual C++ 20;Microsoft .NET Framework;Windows SDK;Microsoft Visual C++ 2005;Microsoft Visual C++ 2008;Microsoft Visual C++ 2010;Microsoft Visual C++ 2012;Microsoft Visual C++ 2013;Microsoft Visual C++ 2015;Microsoft Visual C++ 2017;Microsoft Visual C++ 2019;Microsoft Visual C++ 2022;Microsoft .NET Core;Microsoft .NET Desktop Runtime;Microsoft ASP.NET Core;Windows Software Development Kit;Microsoft Help Viewer;WinRT Intellisense;Windows Applic [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string ExcludePatterns {
            get {
                return ResourceManager.GetString("ExcludePatterns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Intel Corporation;NVIDIA Corporation;Realtek;Oracle Corporation.
        /// </summary>
        internal static string ExcludePublishers {
            get {
                return ResourceManager.GetString("ExcludePublishers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Visual Studio Code:Développement;Visual Studio 2019:Développement;Visual Studio 2022:Développement;Git:Développement;GitHub Desktop:Développement;Docker Desktop:Développement;Node.js:Développement;Python:Développement;Android Studio:Développement;Unity:Développement;Postman:Développement;Notepad++:Développement;Google Chrome:Navigateurs;Mozilla Firefox:Navigateurs;Microsoft Edge:Navigateurs;Opera:Navigateurs;Brave:Navigateurs;VLC media player:Multimédia;Spotify:Multimédia;iTunes:Multimédia;Audacity:Multiméd [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string KnownSoftware {
            get {
                return ResourceManager.GetString("KnownSoftware", resourceCulture);
            }
        }
    }
}
